config/routes.rb
Rails.application.routes.draw do
  # get "sign_up", to: "organizations#new", as: :new_user_registration
  get "sign_up", to: "organizations#new", as: :new_user_registration
  devise_for :users, skip: [:registration, :session]
  as :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    post "sign_in", to: "devise/sessions#create", as: :user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    get "users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "users", to: "devise/registrations#update", as: :user_registration
  end
  
  root "pages#home"

  # Customer Account
  namespace :account do
    get "dashboard", to: "dashboard#index", as: :dashboard
    resources :notes
    resources :documents
    resources :saved_templates
    resources :organizations, only: [:edit, :update]
    resources :users, only: [:index] do
      member do
        patch :resend_invitation
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :documents, only: [:index, :show]
    end
  end

  # Public
  resources :organizations, only: [:new, :create]
  resources :documents, only: [:index, :show]

end

app/views/partials/_navigation.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <% if request.url.include?("account") %>
      <label for="my-drawer-2" class="btn btn-ghost drawer-button lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </label>
    <% end %>
    <%= link_to current_tenant ? current_tenant.name : "KnowKnow", root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>
  <div class="flex-none hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <% if user_signed_in? %>
        <li><%= link_to "Dashboard", account_dashboard_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>

  <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
        </svg>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-2 p-2 shadow bg-base-100 rounded-box w-52">
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", account_dashboard_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
</div>