config/routes.rb
Rails.application.routes.draw do
  # get "sign_up", to: "organizations#new", as: :new_user_registration
  get "sign_up", to: "organizations#new", as: :new_user_registration
  devise_for :users, skip: [:registration, :session]
  as :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    post "sign_in", to: "devise/sessions#create", as: :user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    get "users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "users", to: "devise/registrations#update", as: :user_registration
  end
  
  root "pages#home"

  # Customer Account
  namespace :account do
    get "dashboard", to: "dashboard#index", as: :dashboard
    resources :notes
    resources :documents
    resources :saved_templates
    resources :organizations, only: [:edit, :update]
    resources :users, only: [:index] do
      member do
        patch :resend_invitation
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :documents, only: [:index, :show]
    end
  end

  # Public
  resources :organizations, only: [:new, :create]
  resources :documents, only: [:index, :show]

end

app/models/document.rb
class Document < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_tenant :organization
  belongs_to :user
  has_rich_text :content

  has_one :action_text_rich_text,
    class_name: 'ActionText::RichText',
    as: :record

  validates :title, presence: true, length: { maximum: 50 }
end

app/controllers/account/documents_controller.rb
class Account::DocumentsController < AccountController
  before_action :set_document, only: %i[ show edit update destroy ]

  def index
    @documents = current_user.documents.all
    authorize @documents
  end

  def show
  end

  def new
    @document = Document.new
    authorize @document
  end

  def create
    @document = current_user.documents.new(document_params)
    authorize @document

    respond_to do |format|
      if @document.save
        format.html { redirect_to account_document_url(@document), notice: "Document was successfully created."}
      else
        format.html { render :new, status: :unprocessable_entity } 
      end
    end 
  end

  def edit
  end

  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to account_document_url(@document), notice: "Document was successfully updated."}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to account_documents_url, notice: "Document was successfully delete."}
    end
  end

  private
    def document_params
      params.require(:document).permit(:title, :content, :published, :internal)
    end

    def set_document
      @document = Document.friendly.find(params[:id])
      authorize @document
    end
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApiController
 def index
   @documents = Document.all
 end

 def show
   @document = Document.friendly.find(params[:id])
 end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    if user_signed_in? && current_user.organization == current_tenant
      @documents = Document.order("updated_at DESC").where(published: true).or(Document.where(internal: true))
    else
      @documents = Document.order("updated_at DESC").where(published: true, internal: false)
    end

    @documents = @documents.joins(:action_text_rich_text)
      .where("action_text_rich_texts.body Like ?", "%#{params[:query]}%") if params[:query].present?

    @pagy, @documents = pagy(@documents.all, items: 2)
  end

  def show
    @document = Document.friendly.find(params[:id])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def bg_color
    current_tenant.present? ? current_tenant.background_color : ""
  end

  def tx_color
    current_tenant.present? ? current_tenant.text_color : ""
  end
end

app/views/documents/index.html.erb
<header class="hero h-96 bg-base-200" style="background-color:<%= bg_color %>; color:<%= tx_color %>;">
  <div class="hero-content text-center">
    <div class="max-w-lg">
      <h1 class="text-4xl mb-6 font-semibold mr-auto"><%= current_tenant.heading %></h1>
      <h4 class="text-xl mb-6 font-semibold mr-auto"><%= current_tenant.sub_heading %></h4>
      <div>
        <%= form_with url: documents_path, method: :get, data: { controller: "search-form",
                                                                 turbo_action: "advance",
                                                                 turbo_frame: "documents" } do |form| %>
          <%= form.text_field :query,
            placeholder: "Search Knowledge Base", 
            class: "input input-bordered w-full", 
            autocomplete: "off", 
            data: { action: "input->search-form#search" } 
          %>
        <% end %>
      </div>
    </div>
  </div>
</header>
<section class="my-8 max-w-4xl mx-auto">
  <div>
    <%= turbo_frame_tag "documents" do %>
      <% @documents.each do |document| %>
        <div class="card w-full border-t-4 rounded-none bg-gray-50">
          <div class="card-body">
            <h2 class="card-title"><%= document.title %></h2>
            <p><%= truncate((document.content.to_plain_text), length: 50) %></p>
            <div class="card-actions justify-end">
              <%= link_to "Read more →", document_path(document), class: "btn btn-ghost btn-sm" %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="my-2">
        <%== pagy_nav(@pagy, link_extra: 'data-turbo-action="advance"') if @pagy.pages > 1 %>
      </div>
    <% end %>
  </div>
</section>

app/views/documents/show.html.erb
<div id="<%= dom_id @document %>">
  <article class="prose max-w-4xl mx-auto px-4">
   <h1 class="">
    <%= @document.title %>
   </h1> 
   <div class="text-sm">
     <p>Updated: <%= @document.updated_at.strftime("%m/%d/%Y") %></p>
   </div>
   <% if @document.internal %>
    <div class="badge badge-error badge-lg font-bold">
      Internal Only 
    </div>
   <% end %>
   <section>
      <%= @document.content %>
    </section>
  </article>
</div>