config/routes.rb
Rails.application.routes.draw do
  # get "sign_up", to: "organizations#new", as: :new_user_registration
  get "sign_up", to: "organizations#new", as: :new_user_registration
  devise_for :users, skip: [:registration, :session]
  as :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    post "sign_in", to: "devise/sessions#create", as: :user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    get "users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "users", to: "devise/registrations#update", as: :user_registration
  end
  
  root "pages#home"

  # Customer Account
  namespace :account do
    get "dashboard", to: "dashboard#index", as: :dashboard
    resources :notes
    resources :documents
    resources :saved_templates
    resources :organizations, only: [:edit, :update]
    resources :users, only: [:index] do
      member do
        patch :resend_invitation
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :documents, only: [:index, :show]
    end
  end

  # Public
  resources :organizations, only: [:new, :create]
  resources :documents, only: [:index, :show]

end

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knowknow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="drawer drawer-mobile">
      <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <%= render "partials/navigation" %>
        <% if notice %>
          <div class="alert alert-success shadow-lg">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
             <span><%= notice %></span>
            </div>
          </div>
        <% elsif alert %>
          <div class="alert alert-error shadow-lg">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              <span><%= alert %></span>
            </div>
          </div>
        <% end %>

        <%= yield %>

      </div> 
      <div class="drawer-side">
        <label for="my-drawer-2" class="drawer-overlay"></label> 
        <ul class="menu p-4 w-64 bg-gray-200 text-base-content">
          <li class="mt-2 mx-4 font-semibold"><%= current_user.email %></li>
          <div class="divider"></div>
          <!-- Sidebar content here -->
          <li><%= link_to "Notes", account_notes_path %></li>
          <li><%= link_to "Documents", account_documents_path %></li>
          <li><%= link_to "Templates", account_saved_templates_path %></li>
          <% if policy(:user).index? %>
            <li><%= link_to "Theme", edit_account_organization_path(current_tenant.id) %></li>
            <li><%= link_to "Users", account_users_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knowknow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "partials/navigation" %>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>